version: "3.8"

# 申明同一个网络
networks:
  python3:
    name: python3
    # external: true # 申明网络已经在外部创建

    # 数据卷
    # volumes:
    #   consuldata:
    #     # external:true # 申明卷已经在外部创建
    #     name: consuldata

    # 服务
services:
  python3:
    build:
      #指定  Dockerfile  所在文件夹的路径
      context: ./
      # 指定  Dockerfile  文件名
      dockerfile: .dockerfile
    networks:
      python3: # command: [ "mongod", "-f", "/etc/mongo/mongod.conf" ]
    volumes:
      - ../:/home/liwei/code/python:rw
      - /data/lush-dev/liwei:/data/lush-dev/liwei
    restart: on-failure
    stdin_open: true
    # 模拟一个伪终端
    tty: true
    user: 2036:2036
    working_dir: /home/liwei/code/python
    environment:
      - PYTHONDONTWRITEBYTECODE=1
  # http:
  #   build:
  #     #指定  Dockerfile  所在文件夹的路径
  #     context: ./
  #     # 指定  Dockerfile  文件名
  #     dockerfile: Dockerfile.golang
  #   command: [ "http", "true" ]
  #   volumes:
  #     # GOPATH目录
  #     - ../:/go/src/cy/game:rw
  #   labels:
  #     - name="liwei"
  #   # working_dir: /go/src
  #   # 打开标准输入，可以接受外部输入
  #   stdin_open: true
  #   # 模拟一个伪终端
  #   tty: true
  #   # 指定启动顺序
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - consul
  #   networks:
  #     - homework1
  #   ports:
  #     - 8082:8082
  #   environment:
  #     # 设置节点类型
  #     NodeType: http
  #     NodeName: http
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1000k"
  #       max-file: "20"
  #   restart: on-failure